chore: improve commit message validation

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -7,6 +7,9 @@ no_color='\033[0m'
 
 echo -e "\n${yellow}Executing commit-msg hook...${no_color}\n"
 
-npx --no -- commitlint --edit ${1}
+npx --no -- commitlint --edit ${1} || {
+  echo -e "${red}Git commit-msg hook failed! Please use conventional commit format.${no_color}\n"
+  exit 1
+}
 
 echo -e "${green}Git commit-msg hook was successful!${no_color}\n"
